### ISSUE TITLE
Develop Timelock transparency Dashboard

### ISSUE THREAD

**Issue by sajanrajdev** [ebtc-protocol/ebtc-multisig#6]
Develop a dashboard for ease of access to the state of every transaction loaded to the timelocks and the necessary information for both users and reviewers:
- Timelock load time
- Timelock end time
- Transaction info (what change to the system it will introduce)
- Links to simulation of execution
- Multisig that loaded it
- Salt
- Tx ID
- TX status: Timelocked, Ready to execute, cancelled or executed

Nice to have: 
For each timelock
- Permissioned actors audit
- Current min delay

**Comment by petrovska-petro** [comment]
should not be this part of ui or f/e team ticketing?

**Comment by sajanrajdev** [comment]
> should not be this part of ui or f/e team ticketing?

The UI team has their hands full until after launch so we decided that the development of the MVP can be handled by the multisig pod with their guidance. This will be a functional version so that users and reviewers can refer to from the get to. Once their bandwidth allows it, the UI team will take it over and improve.

**Comment by sajanrajdev** [comment]
After discussions with the UI team, we decided that a Dune Dashboard should be enough for an MVP. The scope is the same. As bandwidth allows, the UI team will work on a custom made version.

**Comment by petrovska-petro** [comment]
can handle the dune at my end

**Comment by petrovska-petro** [comment]
during the initial phases dune dash was explored as a solution, but it is foreseen to required lots of workarounds into decoding and a separate/standalone ui exposing timelock via subgraph likely will be easier to develop in JS stack

in lack of existing timelock deployed on sepolia to have all wired up already the tentative workaround was to leverage an existing timelock in mainnet and a latter stage replace with the mainnet address once the address was added into the dune books

items:

## new contracts for decoding abi

- https://dune.com/contracts/new

## roles tracking

in dune that was doable via events emitted in the access control sc, when revoking or granting. which was simply achivable by decoding the contract in dune and having those evens out of the box `RoleGranted` & `RoleRevoked`

can imagine querying those w/ JS are more straight fwd on the updates

## tx statuses 

in dune was doable only by overridden the status using again events once a tx was schedule w/ status pending. think: `CallExecuted`, `Cancelled`, `CallScheduled`

## samples w/ persistent challenge of data decoding:

- https://dune.com/mahadao/timelock

sources to facilitate decoding of the data given its relatively limit amount of "actions" that will go thru the timelock, in the standalone ui will be simpler to decode as you can have the abi/signatures and digest smoothly

sources: 

1. https://dune.com/queries/1299528
2. https://dune.com/agaperste/event-and-function-signature-sleuthing
4. https://joshua-data.medium.com/intro-to-encoding-and-decoding-ethereum-contract-functions-0e12583916aa
4. https://alexkroeger.mirror.xyz/0C3EQBtFqAK4k2TAGPZhg0JMY-upfTAxuTD-o91vBPc

**Comment by sajanrajdev** [comment]
Dashboard was built as a React project leveraging The Graph: https://github.com/ebtc-protocol/timelock-dashboard
Live deploy: http://www.timelock.ebtc.finance/
